version: "3"

networks:
  monreseau:
    external: false

services:
  db:
    image: postgres:latest
    container_name: db-comput
    environment:
      DATABASE_URL: postgres://strat:admin@0.0.0.0:5432/counter-td1
    ports:
      - "5434:5432"
    networks:
      - monreseau
  back:
    image: td1-comput
    build:
      context: .
      dockerfile: Dockerfile
    container_name: td1-comput-container
    networks:
      - monreseau
    ports:
      - "8080:8080"
    
    