/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 2G+t/tQ+bYrWy6CaGrSaAFViv1wdVlWQBu0EADcD3360jOxx1EwivGvypipsbu7GerU3jtpwk1bPzQRrhdixVA==
 */

/* eslint-disable */
// tslint:disable

import Connections, {Connections_InsertParameters} from './connections'

interface DatabaseSchema {
  connections: {record: Connections, insert: Connections_InsertParameters};
}
export default DatabaseSchema;

function serializeValue(_tableName: string, _columnName: string, value: unknown): unknown {
  return value;
}
export {serializeValue}

export type {
  Connections,
  Connections_InsertParameters,
}
